redis_autocomplete:
  test: localhost:6379
redis_general:
  test: localhost:6379
redis_hits:
  test: localhost:6380
redis_kudos:
  test: localhost:6380
redis_resque:
  test: localhost:6381
redis_rollout:
  test: localhost:6381
