tasks:
  # See https://github.com/gitpod-io/gitpod/issues/7122
  - name: Configure Git committer email
    before: |
      git config --global user.email "${GIT_COMMITTER_EMAIL:-$(git config user.email)}"
  - init: ./script/docker/init.sh
    command: docker compose up -d web

ports:
  - port: 3000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 9300
    onOpen: ignore
  - port: 9400
    onOpen: ignore
