# Available linter versions:
# http://help.houndci.com/en/articles/2461415-supported-linters

jshint:
  config_file: .jshintrc
  ignore_file: .jshintignore

rubocop:
  version: 1.22.1
  config_file: .rubocop.yml
