phraseapp:
  project_id: a3667b8095533c2b3f8d3ac946bb642f
  push:
    sources:
    - file: ./config/locales/<tag>/<locale_name>.yml
      params:
        file_format: yml
  pull:
    targets:
      # defaults
      - file: ./config/locales/defaults/<locale_name>.yml
        params:
          file_format: yml
          tag: defaults
      # devise
      - file: ./config/locales/devise/<locale_name>.yml
        params:
          file_format: yml
          tag: devise
      # mailers
      - file: ./config/locales/mailers/<locale_name>.yml
        params:
          file_format: yml
          tag: mailers
      # models
      - file: ./config/locales/models/<locale_name>.yml
        params:
          file_format: yml
          tag: models
      # validators
      - file: ./config/locales/validators/<locale_name>.yml
        params:
          file_format: yml
          tag: validators
      # views
      - file: ./config/locales/views/<locale_name>.yml
        params:
          file_format: yml
          tag: views
