# options available at https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.3

# stop checking for ambiguous regexp literal
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# stop checking line length
Metrics/LineLength:
  Enabled: false

# prefer template tokens (like %{foo}) over annotated tokens (like %s)
Style/FormatStringToken:
  EnforcedStyle: template

# stop checking if uses of "self" are redundant
Style/RedundantSelf:
  Enabled: false

# stop checking quotation marks
Style/StringLiterals:
  Enabled: false

# stop checking for trailing whitespace
Style/TrailingWhitespace:
  Enabled: false
