# options available at https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.6

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/TrailingWhitespace:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# prefer template tokens (like %{foo}) over annotated tokens (like %s)
Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $elasticsearch
    - $rollout

# stop checking if uses of "self" are redundant
Style/RedundantSelf:
  Enabled: false

# stop checking quotation marks
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
