server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.debug": true

server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.debug": true

browser_caps:
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "Edge"
    "browser_version": "14.0"
    "resolution": "1600x1200"
