server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.debug": true

server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.debug": true

browser_caps:
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "IE"
    "browser_version": "11.0"
    "resolution": "1024x768"
