server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.debug": true

browser_caps:
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "Firefox"
    "browser_version": "51.0 beta"
    "resolution": "1440x900"
