development:
  secret_key_base: <%= ArchiveConfig.SESSION_SECRET %>

test:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 
staging:
  secret_key_base: <%= ArchiveConfig.SESSION_SECRET %>
  lockup_codeword: <%= ArchiveConfig.LOCKUP_CODEWORD %>
  lockup_hint: <%= ArchiveConfig.LOCKUP_HINT %>

production:
  secret_key_base: <%= ArchiveConfig.SESSION_SECRET %>
