#!/bin/sh
./script/gem_security.sh 
if [  $? -ne 0 ] ; then 
  exit 1
fi
ERRORS=`find app -iname "*.rb" -print0 | xargs -0 -n 1 ./script/check_syntax_file`
if [ -z "${ERRORS}" ] ; then 
  exit 0
fi
exit 1
