#!/bin/sh
./script/gem_security.sh
if [  $? -ne 0 ] ; then
  exit 1
fi
echo "This should be READ-COMMITTED"
mysql -e "SHOW VARIABLES LIKE 'tx_isolation';"
mysql -e "SHOW VARIABLES LIKE 'tx_isolation';" | grep -s "READ-COMMITTED"
if [  $? -ne 0 ] ; then 
  exit 1
fi
ERRORS=`find app lib -iname "*.rb" -print0 | xargs -0 -n 1 ./script/check_syntax_file`
if [ -z "${ERRORS}" ] ; then 
  exit 0
fi
exit 1
