#!/usr/bin/env script/runner
# usage:
# RAILS_ENV=production script/ensure_required_tags.rb

Warning.create_canonical(ArchiveConfig.WARNING_DEFAULT_TAG_NAME)
Warning.create_canonical(ArchiveConfig.WARNING_NONE_TAG_NAME)
Warning.create_canonical(ArchiveConfig.WARNING_VIOLENCE_TAG_NAME)
Warning.create_canonical(ArchiveConfig.WARNING_DEATH_TAG_NAME)
Warning.create_canonical(ArchiveConfig.WARNING_NONCON_TAG_NAME)
Warning.create_canonical(ArchiveConfig.WARNING_CHAN_TAG_NAME)
Rating.create_canonical(ArchiveConfig.RATING_DEFAULT_TAG_NAME, true)
Rating.create_canonical(ArchiveConfig.RATING_EXPLICIT_TAG_NAME, true)
Rating.create_canonical(ArchiveConfig.RATING_MATURE_TAG_NAME, true)
Rating.create_canonical(ArchiveConfig.RATING_TEEN_TAG_NAME, false)
Rating.create_canonical(ArchiveConfig.RATING_GENERAL_TAG_NAME, false)
Category.create_canonical(ArchiveConfig.CATEGORY_HET_TAG_NAME)
Category.create_canonical(ArchiveConfig.CATEGORY_SLASH_TAG_NAME)
Category.create_canonical(ArchiveConfig.CATEGORY_FEMSLASH_TAG_NAME)
Category.create_canonical(ArchiveConfig.CATEGORY_GEN_TAG_NAME)
Category.create_canonical(ArchiveConfig.CATEGORY_MULTI_TAG_NAME)
Category.create_canonical(ArchiveConfig.CATEGORY_OTHER_TAG_NAME)
Media.create_canonical(ArchiveConfig.MEDIA_UNCATEGORIZED_NAME)
Media.create_canonical(ArchiveConfig.MEDIA_NO_TAG_NAME)
Fandom.create_canonical(ArchiveConfig.FANDOM_NO_TAG_NAME)
