# Based on https://github.com/tk0miya/action-erblint/blob/main/README.md#example-usage

name: Reviewdog

on: [pull_request]

permissions:
  checks: write

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: linters
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Ruby and run bundle install
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: rubocop
        uses: reviewdog/action-rubocop@b6d5e953a5fc0bf3ab65254e77730ea2174d6d6d
        with:
          use_bundler: true
          reporter: github-pr-check
          skip_install: true
          fail_level: any

  erb_lint:
    name: ERB Lint runner
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: linters
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Ruby and run bundle install
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: erb_lint
        uses: otwcode/action-erblint@ece7c46883ef6a311194b9be3e6a2837945898e7
        with:
          use_bundler: true
          reporter: github-pr-check
          fail_level: any
          config_file: .erb-lint.yml
